premiere
robertocastro/heroes pull request #2
Opened 2022-09-13 15:29 UTC by viince98

2022-09-15 20:01 UTC, robertocastro requested changes

2022-09-15 20:01 UTC, robertocastro commented on index.html
> +      <p>Commencer</p>
Je n'aurais pas mis de p dans un button. Ca me fait bizarre de mettre une balise de type block dans une balise de type en ligne. Qu'en penses-tu ?

2022-09-15 20:01 UTC, robertocastro commented on style.css
> +    position: absolute;
Là il faut se méfier de ce que dit Figma qui a l'air de tout positionner en "absolute". D'après moi aucun élément de la maquette ne devrait être positionné en absolute. Les éléments sont suffisamment simple pour gérer le positionnement dans leur flux normal. Veux-tu que l'on fasse un point là-dessus ?

2022-09-15 20:01 UTC, robertocastro commented on style.css
> +    width: 375px;
Tu n'as pas besoin d'ajouter un width à 375px. Le bloc header prendra naturellement toute la place disponible en largeur

2022-09-15 20:01 UTC, robertocastro commented on style.css
> +  font-family: "Inter";
Tu ne devrais pas définir font-family pour chaque élément. tu devrais définir la font comme ceci :  body { font-family : ... } et redéfinir la font dans un élément si c'est une font différente de la font de base.

2022-09-15 20:01 UTC, robertocastro commented on style.css
> +  width: 375px;
Idem que précédemment

2022-09-15 20:01 UTC, robertocastro commented on style.css
> +button p {
Peut-être remplacé le p par un span

2022-09-16 06:01 UTC, viince98 commented
Ok j'ai lu tout ce que tu m'as écris, merci pour les conseils, c'est vrai que certaines erreurs sont vraiment évitables maintenant que je te relis, je te tiens au courant dès lors que c'est corrigé

2022-09-16 14:10 UTC, robertocastro approved these changes

2022-09-16 14:11 UTC, merged